[ loadI 8 => r3 ; loadI 12 => r4 ]
[ add r3,r4 => r1 ; nop ]
[ load r1 => r0 ; nop ]
[ load r3 => r2 ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ store r0 => r1 ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ output 12  ; nop ]

