// Average Ready Queue Length: 0
// COMP 412, Lab 3 Reference Implementation
[ loadI  8 => r0 ; loadI  12 => r4 ]
[ load   r0 => r3 ; nop ]
[ load   r4 => r5 ; nop ]
[ nop    ; nop ]
[ nop    ; nop ]
[ nop    ; nop ]
[ add    r0, r3  => r2 ; nop ]
[ store  r2 => r4 ; sub    r2, r3  => r1 ]
[ nop    ; nop ]
[ nop    ; nop ]
[ nop    ; nop ]
[ nop    ; nop ]
[ output 8 ; nop ]
[ store  r1 => r0 ; nop ]
[ nop    ; nop ]
[ nop    ; nop ]
[ nop    ; nop ]
[ nop    ; nop ]
[ output 8 ; nop ]
