[ loadI 8 => r2 ; loadI 12 => r1 ]
[ nop ; mult r2,r1 => r3 ]
[ nop ; nop ]
[ nop ; nop ]
[ add r2,r3 => r0 ; nop ]
[ store r0 => r1 ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ output 12  ; nop ]

