[ loadI 8 => r1 ; loadI 12 => r4 ]
[ load r1 => r3 ; nop ]
[ load r4 => r5 ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ add r1,r3 => r2 ; nop ]
[ store r2 => r4 ; sub r2,r3 => r0 ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ output 8  ; nop ]
[ store r0 => r1 ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ output 8  ; nop ]

