[ loadI 1024 => r2 ; loadI 4 => r4 ]
[ load r2 => r3 ; add r2,r4 => r0 ]
[ load r0 => r1 ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ store r2 => r3 ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ store r0 => r1 ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ nop ; nop ]
[ output 2048  ; nop ]
[ output 2052  ; nop ]

